/*
  Auto-generated by Spline
*/

import useSpline from '@splinetool/r3f-spline'
import { OrthographicCamera } from '@react-three/drei'
import { motion } from 'framer-motion'

export default function Devil2({ pos, ...props }) {
  const { nodes, materials } = useSpline('https://prod.spline.design/tYYYdjgHR1EjcQtv/scene.splinecode')
  return (
    <>
      <color attach="background" args={['#6bb0f9']} />
      <group {...props} dispose={null}>
        <motion.group name="Character 2" position={[209.8 + pos, 59.55, 3.63]} rotation={[0, 0.55, 0]} whileHover={{scale: 1.1}}>
          <group name="Tail" position={[0.73, -33.92, -18.72]}>
            <group name="Group" position={[3.37, 46.95, -55.6]} rotation={[0.12, 0, 0]}>
              <mesh
                name="Cone"
                geometry={nodes.Cone.geometry}
                material={materials['Cone Material']}
                castShadow
                receiveShadow
                position={[0.07, 4.2, -7.15]}
                rotation={[-0.94, -1.4, 0.09]}
                scale={1}
              />
            </group>
            <mesh
              name="tail"
              geometry={nodes.tail.geometry}
              material={materials['tail Material']}
              castShadow
              receiveShadow
              position={[0.89, -0.04, -22.41]}
              rotation={[3.14, 0, -1.49]}
              scale={1}
            />
          </group>
          <mesh
            name="lHorn"
            geometry={nodes.lHorn.geometry}
            material={materials['lHorn Material']}
            castShadow
            receiveShadow
            position={[-36.69, 28.98, 19.87]}
            rotation={[-1.64, -0.5, 1.08]}
            scale={[1, 1, 1.85]}
          />
          <mesh
            name="rHorn"
            geometry={nodes.rHorn.geometry}
            material={materials['rHorn Material']}
            castShadow
            receiveShadow
            position={[31.22, 27.07, 41.13]}
            rotation={[-1.33, 0.61, -1.98]}
            scale={[1, 1, 1.85]}
          />
          <mesh
            name="body"
            geometry={nodes.body.geometry}
            material={materials['body Material']}
            castShadow
            receiveShadow
            position={[0, -10.68, 24.28]}
            rotation={[-Math.PI / 2, 0, -1.91]}
            scale={1}
          />
          <mesh
            name="left eye"
            geometry={nodes['left eye'].geometry}
            material={materials['left eye Material']}
            castShadow
            receiveShadow
            position={[-24.27, -3.63, 57.33]}
            rotation={[-0.2, -0.53, -0.1]}
            scale={0.74}
          />
          <mesh
            name="right eye"
            geometry={nodes['right eye'].geometry}
            material={materials.black}
            castShadow
            receiveShadow
            position={[6.37, -3.94, 65.95]}
            rotation={[-0.22, -0.08, -0.07]}
            scale={0.74}
          />
          <mesh
            name="left eyebrow"
            geometry={nodes['left eyebrow'].geometry}
            material={materials['left eyebrow Material']}
            castShadow
            receiveShadow
            position={[-23.06, 6.68, 53.84]}
            rotation={[0, -0.45, -1.55]}
            scale={1}
          />
          <mesh
            name="right eyebrow"
            geometry={nodes['right eyebrow'].geometry}
            material={materials['right eyebrow Material']}
            castShadow
            receiveShadow
            position={[7.28, 6.17, 61.98]}
            rotation={[0, 0.02, -1.63]}
            scale={1}
          />
          <mesh
            name="left cheek"
            geometry={nodes['left cheek'].geometry}
            material={materials['left cheek Material']}
            castShadow
            receiveShadow
            position={[-30.09, -14.88, 55.2]}
            rotation={[0, -0.61, 0]}
          />
          <mesh
            name="right cheek"
            geometry={nodes['right cheek'].geometry}
            material={materials['right cheek Material']}
            castShadow
            receiveShadow
            position={[11.44, -14.9, 67.41]}
            rotation={[-0.04, -0.12, -0.01]}
            scale={1}
          />
        </motion.group>
        <OrthographicCamera
          name="1"
          makeDefault={true}
          zoom={1.51}
          far={100000}
          near={-100000}
          position={[61.19, 203.97, 362.81]}
          rotation={[-0.2, -0.12, -0.02]}
          scale={1}
        />
        <hemisphereLight name="Default Ambient Light" intensity={0.75} color="#eaeaea" />
      </group>
    </>
  )
}
