/*
  Auto-generated by Spline
*/

import useSpline from '@splinetool/r3f-spline'
import { OrthographicCamera, CameraControls } from '@react-three/drei'

export default function Scene({ ...props }) {
  const { nodes, materials } = useSpline('https://prod.spline.design/5D6-2xSzbGqLHgNH/scene.splinecode')
  return (
    <>
      <group {...props} dispose={null}>
        <mesh
          name="Path 3"
          geometry={nodes['Path 3'].geometry}
          material={materials['Path 3 Material']}
          position={[2032.37, 862.58, 211.44]}
          rotation={[-0.5, -0.52, 0.34]}
        />
        <mesh
          name="Path 2"
          geometry={nodes['Path 2'].geometry}
          material={materials['Path 2 Material']}
          position={[-419.85, 590.07, -749.7]}
          rotation={[-Math.PI / 2, -0.41, -Math.PI / 2]}
          scale={[-1, 1, 0.19]}
        />
        <mesh
          name="Path"
          geometry={nodes.Path.geometry}
          material={materials['Path Material']}
          position={[-651.62, 329.72, -30.32]}
          rotation={[-1.59, -0.02, 0.13]}
          scale={1}
        />
        <group name="Group 4" position={[-628.27, 159.41, 249.03]} rotation={[-0.62, 1.04, 0.4]} scale={1.05}>
          <mesh
            name="Merged Geometry"
            geometry={nodes['Merged Geometry'].geometry}
            material={materials['bee body']}
            castShadow
            receiveShadow
            position={[-165.66, -76.22, -33.25]}
          />
          <mesh
            name="Cube 2"
            geometry={nodes['Cube 2'].geometry}
            material={materials['Cube 2 Material']}
            castShadow
            receiveShadow
            position={[-137.54, -2.02, 65.31]}
            rotation={[-0.89, 0.13, 0.43]}
            scale={[1.47, 1.12, 1.42]}
          />
          <mesh
            name="Cone"
            geometry={nodes.Cone.geometry}
            material={materials['Cone Material']}
            castShadow
            receiveShadow
            position={[-145.06, -42.59, 30.22]}
            rotation={[0.73, 0.46, -0.21]}
            scale={[1.37, 0.62, 1.49]}
          />
          <mesh
            name="Cube 21"
            geometry={nodes['Cube 21'].geometry}
            material={materials['Cube 21 Material']}
            castShadow
            receiveShadow
            position={[-192.83, -0.93, 64]}
            rotation={[-0.96, -0.09, 0.62]}
            scale={[1.4, 1.41, 1.3]}
          />
          <mesh
            name="Cone1"
            geometry={nodes.Cone1.geometry}
            material={materials['Cone1 Material']}
            castShadow
            receiveShadow
            position={[-187.73, -42.59, 30.22]}
            rotation={[0.54, 0.64, 0.11]}
            scale={[1.4, 0.62, 1.41]}
          />
          <directionalLight
            name="Directional Light"
            castShadow
            intensity={0.1}
            shadow-mapSize-width={1024}
            shadow-mapSize-height={1024}
            shadow-camera-near={-10000}
            shadow-camera-far={100000}
            shadow-camera-left={-500}
            shadow-camera-right={500}
            shadow-camera-top={500}
            shadow-camera-bottom={-500}
            position={[215.86, 143.52, 113.29]}
          />
        </group>
        <group name="Group 5" position={[1971.29, 1885.47, -733.26]} rotation={[-1.47, 0.68, 1.34]} scale={1}>
          <mesh
            name="Merged Geometry1"
            geometry={nodes['Merged Geometry1'].geometry}
            material={materials['bee body']}
            castShadow
            receiveShadow
            position={[-165.66, -76.22, -33.25]}
          />
          <mesh
            name="Cube 22"
            geometry={nodes['Cube 22'].geometry}
            material={materials['Cube 22 Material']}
            castShadow
            receiveShadow
            position={[-137.54, -2.02, 65.31]}
            rotation={[-0.89, 0.13, 0.43]}
            scale={[1.47, 1.12, 1.42]}
          />
          <mesh
            name="Cone2"
            geometry={nodes.Cone2.geometry}
            material={materials['Cone2 Material']}
            castShadow
            receiveShadow
            position={[-145.06, -42.59, 30.22]}
            rotation={[0.73, 0.46, -0.21]}
            scale={[1.37, 0.62, 1.49]}
          />
          <mesh
            name="Cube 23"
            geometry={nodes['Cube 23'].geometry}
            material={materials['Cube 23 Material']}
            castShadow
            receiveShadow
            position={[-192.83, -0.93, 64]}
            rotation={[-0.96, -0.09, 0.62]}
            scale={[1.4, 1.41, 1.3]}
          />
          <mesh
            name="Cone3"
            geometry={nodes.Cone3.geometry}
            material={materials['Cone3 Material']}
            castShadow
            receiveShadow
            position={[-187.73, -42.59, 30.22]}
            rotation={[0.54, 0.64, 0.11]}
            scale={[1.4, 0.62, 1.41]}
          />
          <directionalLight
            name="Directional Light1"
            castShadow
            intensity={0.1}
            shadow-mapSize-width={1024}
            shadow-mapSize-height={1024}
            shadow-camera-near={-10000}
            shadow-camera-far={100000}
            shadow-camera-left={-500}
            shadow-camera-right={500}
            shadow-camera-top={500}
            shadow-camera-bottom={-500}
            position={[215.86, 143.52, 113.29]}
          />
        </group>
        <group name="Group 3" position={[-365.86, 779.28, 168.71]} rotation={[1.17, 1.13, -1.13]} scale={1}>
          <mesh
            name="Merged Geometry2"
            geometry={nodes['Merged Geometry2'].geometry}
            material={materials['bee body']}
            castShadow
            receiveShadow
            position={[-165.66, -76.22, -33.25]}
          />
          <mesh
            name="Cube 24"
            geometry={nodes['Cube 24'].geometry}
            material={materials['Cube 24 Material']}
            castShadow
            receiveShadow
            position={[-137.54, -2.02, 65.31]}
            rotation={[-0.89, 0.13, 0.43]}
            scale={[1.47, 1.12, 1.42]}
          />
          <mesh
            name="Cone4"
            geometry={nodes.Cone4.geometry}
            material={materials['Cone4 Material']}
            castShadow
            receiveShadow
            position={[-145.06, -42.59, 30.22]}
            rotation={[0.73, 0.46, -0.21]}
            scale={[1.37, 0.62, 1.49]}
          />
          <mesh
            name="Cube 25"
            geometry={nodes['Cube 25'].geometry}
            material={materials['Cube 25 Material']}
            castShadow
            receiveShadow
            position={[-192.83, -0.93, 64]}
            rotation={[-0.96, -0.09, 0.62]}
            scale={[1.4, 1.41, 1.3]}
          />
          <mesh
            name="Cone5"
            geometry={nodes.Cone5.geometry}
            material={materials['Cone5 Material']}
            castShadow
            receiveShadow
            position={[-187.73, -42.59, 30.22]}
            rotation={[0.54, 0.64, 0.11]}
            scale={[1.4, 0.62, 1.41]}
          />
          <directionalLight
            name="Directional Light2"
            castShadow
            intensity={0.1}
            shadow-mapSize-width={1024}
            shadow-mapSize-height={1024}
            shadow-camera-near={-10000}
            shadow-camera-far={100000}
            shadow-camera-left={-500}
            shadow-camera-right={500}
            shadow-camera-top={500}
            shadow-camera-bottom={-500}
            position={[215.86, 143.52, 113.29]}
          />
        </group>
        <directionalLight
          name="Directional Light 2"
          castShadow
          intensity={0.18}
          shadow-mapSize-width={1024}
          shadow-mapSize-height={1024}
          shadow-camera-near={-10000}
          shadow-camera-far={100000}
          shadow-camera-left={-1000}
          shadow-camera-right={1000}
          shadow-camera-top={1000}
          shadow-camera-bottom={-1000}
          color="#fcfedd"
          position={[0, 1922.77, 0]}
        />
        <mesh
          name="Text"
          geometry={nodes.Text.geometry}
          material={materials['Text Material']}
          castShadow
          receiveShadow
          position={[451.24, -473.62, 1153.09]}
          rotation={[-0.2, 0.17, 0.04]}
        />
        <group
          name="Grass Tall 8"
          position={[876, -230.74, 223.15]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[-0.68, 0.68, 0.44]}
        >
          <mesh
            name="Subdiv 4"
            geometry={nodes['Subdiv 4'].geometry}
            material={materials['Grass 1']}
            castShadow
            receiveShadow
            position={[-25.73, 33.06, 9.24]}
            rotation={[-1.01, -0.45, -1.06]}
            scale={[0.19, 0.12, 0.65]}
          />
          <mesh
            name="Subdiv 41"
            geometry={nodes['Subdiv 41'].geometry}
            material={materials['Grass 1']}
            castShadow
            receiveShadow
            position={[-30.88, 69.94, 9.72]}
            rotation={[-1.37, -0.34, -1.25]}
            scale={[0.34, 0.22, 1.19]}
          />
          <mesh
            name="Subdiv 42"
            geometry={nodes['Subdiv 42'].geometry}
            material={materials['Grass 1']}
            castShadow
            receiveShadow
            position={[0.4, 46.61, -23.07]}
            rotation={[-1.87, -0.02, 2.39]}
            scale={[0.19, 0.12, 0.75]}
          />
        </group>
        <group name="Cloud 2" position={[192.1, 1528.52, 259.61]} scale={1.36}>
          <mesh
            name="Cube"
            geometry={nodes.Cube.geometry}
            material={materials.white}
            receiveShadow
            position={[-0.88, -10.63, 0]}
          />
        </group>
        <group name="Cloud" position={[-303.1, 1336.51, 250.82]} scale={2.37}>
          <mesh
            name="Cube1"
            geometry={nodes.Cube1.geometry}
            material={materials.white}
            receiveShadow
            position={[-0.88, -10.63, 0]}
          />
        </group>
        <group name="Circus" position={[1999.06, -238.43, -130.28]} scale={2.34}>
          <group name="flag" position={[-235.73, 94.57, -136.64]} scale={0.46}>
            <group
              name="Pillar-3"
              position={[187, -40.53, -356.78]}
              rotation={[-Math.PI, 0, -Math.PI]}
              scale={[-1.13, 1, 1.13]}
            >
              <mesh
                name="Sphere 2"
                geometry={nodes['Sphere 2'].geometry}
                material={materials.yellow}
                castShadow
                receiveShadow
                position={[0, 259.85, 0]}
              />
              <mesh
                name="Cylinder 33"
                geometry={nodes['Cylinder 33'].geometry}
                material={materials.pink}
                castShadow
                receiveShadow
                position={[0, 36.32, -1.54]}
                rotation={[0, 0, 0]}
                scale={1}
              />
            </group>
            <group
              name="Pillar-2"
              position={[670.49, -23.96, 347.58]}
              rotation={[-3.06, 0.02, -2.97]}
              scale={[-1.13, 1, 1.13]}
            >
              <mesh
                name="Sphere 21"
                geometry={nodes['Sphere 21'].geometry}
                material={materials.yellow}
                castShadow
                receiveShadow
                position={[0, 98.29, 0]}
              />
              <mesh
                name="Cylinder 331"
                geometry={nodes['Cylinder 331'].geometry}
                material={materials.pink}
                castShadow
                receiveShadow
                position={[0, -56.99, -1.54]}
                rotation={[0, 0, 0]}
                scale={1}
              />
            </group>
            <group
              name="Pillar-1"
              position={[-452.7, 10.34, -349.43]}
              rotation={[3.05, 0.01, 3.05]}
              scale={[-1.13, 1, 1.13]}
            >
              <mesh
                name="Sphere 22"
                geometry={nodes['Sphere 22'].geometry}
                material={materials.yellow}
                castShadow
                receiveShadow
                position={[0, 98.29, 0]}
              />
              <mesh
                name="Cylinder 332"
                geometry={nodes['Cylinder 332'].geometry}
                material={materials.pink}
                castShadow
                receiveShadow
                position={[0, -69.39, -1.54]}
                rotation={[0, 0, 0]}
                scale={1}
              />
            </group>
            <group name="flag-2" position={[434.82, 121.35, -1.56]} rotation={[0, -0.96, -0.17]} scale={[-1, 1, 1]}>
              <mesh
                name="Triangle 3"
                geometry={nodes['Triangle 3'].geometry}
                material={materials.green}
                castShadow
                receiveShadow
                position={[347.33, -1.52, -0.87]}
                rotation={[0, 0, -Math.PI]}
                scale={1}
              />
              <mesh
                name="Triangle 2"
                geometry={nodes['Triangle 2'].geometry}
                material={materials.purple}
                castShadow
                receiveShadow
                position={[399.49, -1.52, -0.87]}
                rotation={[0, 0, -Math.PI]}
                scale={1}
              />
              <mesh
                name="Cylinder 32"
                geometry={nodes['Cylinder 32'].geometry}
                material={materials.yellow}
                castShadow
                receiveShadow
                position={[0, 18.85, -0.63]}
                rotation={[0, 0, -Math.PI / 2]}
                scale={1}
              />
            </group>
            <group
              name="flag-1"
              position={[-251.28, 120.28, -356.26]}
              rotation={[-Math.PI, 0, 2.97]}
              scale={[-1, 1, 1]}
            >
              <mesh
                name="Triangle 31"
                geometry={nodes['Triangle 31'].geometry}
                material={materials.green}
                castShadow
                receiveShadow
                position={[347.33, -1.52, -0.87]}
                rotation={[0, 0, -Math.PI]}
                scale={1}
              />
              <mesh
                name="Triangle 21"
                geometry={nodes['Triangle 21'].geometry}
                material={materials.purple}
                castShadow
                receiveShadow
                position={[399.49, -1.52, -0.87]}
                rotation={[0, 0, -Math.PI]}
                scale={1}
              />
              <mesh
                name="Cylinder 321"
                geometry={nodes['Cylinder 321'].geometry}
                material={materials.yellow}
                castShadow
                receiveShadow
                position={[123.17, 18.85, -0.63]}
                rotation={[0, 0, -Math.PI / 2]}
                scale={1}
              />
            </group>
          </group>
        </group>
        <group name="Carrot 2" position={[1945.83, -207.49, 148.22]} rotation={[0, 0, 0]} scale={0.6}>
          <mesh
            name="Cube 41"
            geometry={nodes['Cube 41'].geometry}
            material={materials.green}
            castShadow
            receiveShadow
            position={[45.41, 243.84, -73.84]}
            rotation={[-0.36, 0.39, -0.02]}
            scale={1.11}
          />
          <mesh
            name="Cube 40"
            geometry={nodes['Cube 40'].geometry}
            material={materials.green}
            castShadow
            receiveShadow
            position={[68.17, 219.31, -88.7]}
            rotation={[-0.36, 0.39, -1.15]}
            scale={1.11}
          />
          <mesh
            name="Cube 39"
            geometry={nodes['Cube 39'].geometry}
            material={materials.red}
            castShadow
            receiveShadow
            position={[-24.48, 162.7, -25.46]}
            rotation={[-0.36, 0.39, -0.8]}
            scale={1.11}
          />
          <mesh
            name="Cube 411"
            geometry={nodes['Cube 411'].geometry}
            material={materials.green}
            castShadow
            receiveShadow
            position={[136.71, 246, -8.49]}
            rotation={[-0.17, 0.2, -0.07]}
            scale={1.11}
          />
          <mesh
            name="Cube 401"
            geometry={nodes['Cube 401'].geometry}
            material={materials.green}
            castShadow
            receiveShadow
            position={[162.38, 223.9, -22.41]}
            rotation={[-0.17, 0.2, -1.2]}
            scale={1.11}
          />
          <mesh
            name="Cube 391"
            geometry={nodes['Cube 391'].geometry}
            material={materials.red}
            castShadow
            receiveShadow
            position={[59.99, 159.13, 10.88]}
            rotation={[-0.17, 0.2, -0.86]}
            scale={1.11}
          />
          <mesh
            name="Cube 7"
            geometry={nodes['Cube 7'].geometry}
            material={materials.basket}
            castShadow
            receiveShadow
            position={[-3.64, 89.73, -2.82]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={1}
          />
        </group>
        <group name="Apple-red" position={[1322.41, -147.5, -37.79]} rotation={[0, 0, -0.4]} scale={0.54}>
          <mesh
            name="leave"
            geometry={nodes.leave.geometry}
            material={materials.leave}
            castShadow
            receiveShadow
            position={[42.5, 117.38, 0.85]}
            rotation={[0, 0, 0.39]}
            scale={[1.6, 1.6, 0.82]}
          />
          <mesh
            name="branch"
            geometry={nodes.branch.geometry}
            material={materials.branch}
            castShadow
            receiveShadow
            position={[-19.06, 120.44, 0.67]}
            rotation={[0, 0, -2.53]}
            scale={1.6}
          />
          <mesh
            name="apple"
            geometry={nodes.apple.geometry}
            material={materials.apple}
            castShadow
            receiveShadow
            position={[0.98, -39.84, 0]}
            rotation={[0, 0, 0]}
            scale={[1.6, 1.6, 2.22]}
          />
        </group>
        <spotLight
          name="Spot Light"
          castShadow
          intensity={1.1}
          angle={Math.PI / 6}
          distance={2251}
          shadow-mapSize-width={1024}
          shadow-mapSize-height={1024}
          shadow-camera-fov={119.99999999999999}
          shadow-camera-near={100}
          shadow-camera-far={100000}
          color="#fef3c4"
          position={[1314.43, 1682.47, -315.72]}
          rotation={[0, 0.26, -0.93]}
          scale={[1, 1, 1.44]}
        />
        <group name="Sun" position={[1051.01, 1335.62, 25.01]} scale={2.07}>
          <mesh
            name="cone"
            geometry={nodes.cone.geometry}
            material={materials.sun}
            castShadow
            receiveShadow
            position={[0, 0, 0]}
            scale={0.46}
          />
          <mesh
            name="sun"
            geometry={nodes.sun.geometry}
            material={materials.sun}
            castShadow
            receiveShadow
            scale={[1.63, 1.65, 1.63]}
          />
        </group>
        <mesh
          name="pink farm"
          geometry={nodes['pink farm'].geometry}
          material={materials['pink farm Material']}
          receiveShadow
          position={[464.45, -179.53, 605.89]}
          rotation={[-0.11, 0.15, 0.02]}
        />
        <group name="pig" position={[1714.5, -1.78, -190.24]} rotation={[-0.05, -0.5, -0.12]} scale={1}>
          <group name="Text1" position={[-169.64, 226.93, -141.79]} scale={1.5}>
            <mesh
              name="z 3"
              geometry={nodes['z 3'].geometry}
              material={materials.eyes}
              receiveShadow
              position={[3.31, 3.86, 150.26]}
              rotation={[0.02, 0.34, 0.48]}
              scale={1.52}
            />
            <mesh
              name="z 2"
              geometry={nodes['z 2'].geometry}
              material={materials.eyes}
              receiveShadow
              position={[11.01, -36.59, 147.35]}
              rotation={[0, 0.34, -0.38]}
              scale={2.6}
            />
            <mesh
              name="z"
              geometry={nodes.z.geometry}
              material={materials.eyes}
              receiveShadow
              position={[-1.86, -104.19, 151.91]}
              rotation={[0, 0.34, 0.19]}
              scale={3.54}
            />
          </group>
          <mesh
            name="Cube 6"
            geometry={nodes['Cube 6'].geometry}
            material={materials.paws}
            castShadow
            receiveShadow
            position={[167.65, -152.58, -178.74]}
            rotation={[-2.81, 0.95, 2.45]}
            scale={1.04}
          />
          <mesh
            name="Cube 5"
            geometry={nodes['Cube 5'].geometry}
            material={materials.paws}
            castShadow
            receiveShadow
            position={[-29.35, -167.45, -266.58]}
            rotation={[3, -0.19, 2.58]}
            scale={1.04}
          />
          <mesh
            name="Cube 71"
            geometry={nodes['Cube 71'].geometry}
            material={materials.paws}
            castShadow
            receiveShadow
            position={[217.47, -168.06, -10.36]}
            rotation={[2.54, 1.09, -2.53]}
            scale={1.04}
          />
          <mesh
            name="Cube 4"
            geometry={nodes['Cube 4'].geometry}
            material={materials.paws}
            castShadow
            receiveShadow
            position={[-188.55, -183.01, 29.42]}
            rotation={[0.53, -0.71, 0.76]}
            scale={1.04}
          />
          <mesh
            name="Helix"
            geometry={nodes.Helix.geometry}
            material={materials.skin}
            castShadow
            receiveShadow
            position={[75.7, 67.2, -129.32]}
            scale={1.16}
          />
          <mesh
            name="Ellipse 2"
            geometry={nodes['Ellipse 2'].geometry}
            material={materials.paws}
            castShadow
            receiveShadow
            position={[-32.38, -155.19, 319.79]}
            rotation={[0.16, -0.21, 0.21]}
            scale={1.8}
          />
          <mesh
            name="Ellipse"
            geometry={nodes.Ellipse.geometry}
            material={materials.paws}
            castShadow
            receiveShadow
            position={[-77.17, -163.33, 308.62]}
            rotation={[0.16, -0.21, 0.21]}
            scale={1.8}
          />
          <mesh
            name="Cube 42"
            geometry={nodes['Cube 42'].geometry}
            material={materials.skin}
            castShadow
            receiveShadow
            position={[-9.67, -146.38, -182.81]}
            rotation={[1.27, -0.06, -0.38]}
            scale={[-1.11, 1.27, 1.28]}
          />
          <mesh
            name="Cube 43"
            geometry={nodes['Cube 43'].geometry}
            material={materials.skin}
            castShadow
            receiveShadow
            position={[98.04, -150.27, -125.52]}
            rotation={[1.18, 0.09, 0.92]}
            scale={1.29}
          />
          <mesh
            name="Cube 44"
            geometry={nodes['Cube 44'].geometry}
            material={materials.skin}
            castShadow
            receiveShadow
            position={[-125.33, -146.38, -11.98]}
            rotation={[1.35, 0.27, -1.74]}
            scale={[-1.41, 1.16, 1.34]}
          />
          <mesh
            name="Cube 45"
            geometry={nodes['Cube 45'].geometry}
            material={materials.skin}
            castShadow
            receiveShadow
            position={[146.68, -152.11, 38.05]}
            rotation={[1.18, 0.09, 0.92]}
            scale={1.29}
          />
          <mesh
            name="Cube 26"
            geometry={nodes['Cube 26'].geometry}
            material={materials.skin}
            castShadow
            receiveShadow
            position={[19.73, -87.44, -57.83]}
            rotation={[3.14, 0.24, 2.96]}
            scale={[3.72, 3.51, 3.72]}
          />
          <mesh
            name="Torus"
            geometry={nodes.Torus.geometry}
            material={materials.eyes}
            castShadow
            receiveShadow
            position={[-100.7, -86.33, 210.43]}
            rotation={[-0.39, -0.68, -2.44]}
            scale={[-1.74, 1.77, 1.78]}
          />
          <mesh
            name="Torus1"
            geometry={nodes.Torus1.geometry}
            material={materials.eyes}
            castShadow
            receiveShadow
            position={[9.65, -65.36, 237.77]}
            rotation={[-0.44, 0.11, 2.59]}
            scale={1.8}
          />
          <mesh
            name="Cube 13"
            geometry={nodes['Cube 13'].geometry}
            material={materials.skin}
            castShadow
            receiveShadow
            position={[-105.73, -43.01, 88.67]}
            rotation={[1.11, -0.98, 1.7]}
            scale={[-2.41, 2.07, 2.15]}
          />
          <mesh
            name="Cube 131"
            geometry={nodes['Cube 131'].geometry}
            material={materials.skin}
            castShadow
            receiveShadow
            position={[47.14, -13.14, 126.4]}
            rotation={[0.36, 0.76, -0.71]}
            scale={[2.35, 1.9, 1.9]}
          />
          <mesh
            name="Cube 3"
            geometry={nodes['Cube 3'].geometry}
            material={materials.nose}
            castShadow
            receiveShadow
            position={[-22.8, -105.58, 148.31]}
            rotation={[-0.01, -0.24, 0.18]}
            scale={1.8}
          />
          <mesh
            name="Cube2"
            geometry={nodes.Cube2.geometry}
            material={materials.skin}
            castShadow
            receiveShadow
            position={[-18.96, -105.66, 132.88]}
            rotation={[-0.01, -0.24, 0.18]}
            scale={1.8}
          />
        </group>
        <group name="Grass 4" position={[268.01, -199, 570.07]}>
          <mesh
            name="Cube3"
            geometry={nodes.Cube3.geometry}
            material={materials.plants}
            castShadow
            receiveShadow
            position={[-60.28, 6.61, -16.31]}
            rotation={[-1.38, 0.08, -0.17]}
            scale={[0.47, 0.25, 0.02]}
          />
          <mesh
            name="Cube4"
            geometry={nodes.Cube4.geometry}
            material={materials.plants}
            castShadow
            receiveShadow
            position={[-18.08, 16.61, 60.44]}
            rotation={[-1.86, 0.08, 1.13]}
            scale={[0.5, 0.23, 0.03]}
          />
          <mesh
            name="Cube5"
            geometry={nodes.Cube5.geometry}
            material={materials.plants}
            castShadow
            receiveShadow
            position={[56.31, 9.21, -34.78]}
            rotation={[-1.45, -0.02, -2.62]}
            scale={[0.45, 0.25, 0.02]}
          />
          <mesh
            name="Cube6"
            geometry={nodes.Cube6.geometry}
            material={materials.plants}
            castShadow
            receiveShadow
            position={[51.82, -5.82, 43.29]}
            rotation={[-1.44, -0.06, 2.54]}
            scale={[0.5, 0.24, 0.02]}
          />
          <mesh
            name="Cube7"
            geometry={nodes.Cube7.geometry}
            material={materials.plants}
            castShadow
            receiveShadow
            position={[-7.08, 24.92, -67.84]}
            rotation={[-1.13, 0.01, -1.51]}
            scale={[0.52, 0.23, 0.03]}
          />
        </group>
        <group
          name="Grass Tall 7"
          position={[-1121.1, -299.19, 223.15]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[-0.68, 0.68, 0.44]}
        >
          <mesh
            name="Subdiv 43"
            geometry={nodes['Subdiv 43'].geometry}
            material={materials['Grass 1']}
            castShadow
            receiveShadow
            position={[-25.73, 33.06, 9.24]}
            rotation={[-1.01, -0.45, -1.06]}
            scale={[0.19, 0.12, 0.65]}
          />
          <mesh
            name="Subdiv 44"
            geometry={nodes['Subdiv 44'].geometry}
            material={materials['Grass 1']}
            castShadow
            receiveShadow
            position={[-30.88, 69.94, 9.72]}
            rotation={[-1.37, -0.34, -1.25]}
            scale={[0.34, 0.22, 1.19]}
          />
          <mesh
            name="Subdiv 45"
            geometry={nodes['Subdiv 45'].geometry}
            material={materials['Grass 1']}
            castShadow
            receiveShadow
            position={[0.4, 46.61, -23.07]}
            rotation={[-1.87, -0.02, 2.39]}
            scale={[0.19, 0.12, 0.75]}
          />
        </group>
        <group
          name="Grass Tall 4"
          position={[876, -230.74, 223.15]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[-0.68, 0.68, 0.44]}
        >
          <mesh
            name="Subdiv 46"
            geometry={nodes['Subdiv 46'].geometry}
            material={materials['Grass 1']}
            castShadow
            receiveShadow
            position={[-25.73, 33.06, 9.24]}
            rotation={[-1.01, -0.45, -1.06]}
            scale={[0.19, 0.12, 0.65]}
          />
          <mesh
            name="Subdiv 47"
            geometry={nodes['Subdiv 47'].geometry}
            material={materials['Grass 1']}
            castShadow
            receiveShadow
            position={[-30.88, 69.94, 9.72]}
            rotation={[-1.37, -0.34, -1.25]}
            scale={[0.34, 0.22, 1.19]}
          />
          <mesh
            name="Subdiv 48"
            geometry={nodes['Subdiv 48'].geometry}
            material={materials['Grass 1']}
            castShadow
            receiveShadow
            position={[0.4, 46.61, -23.07]}
            rotation={[-1.87, -0.02, 2.39]}
            scale={[0.19, 0.12, 0.75]}
          />
        </group>
        <group
          name="Grass Tall 3"
          position={[1153.86, -238.99, -394.29]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[-0.56, 0.56, 0.37]}
        >
          <mesh
            name="Subdiv 49"
            geometry={nodes['Subdiv 49'].geometry}
            material={materials['Grass 1']}
            castShadow
            receiveShadow
            position={[-25.73, 33.06, 9.24]}
            rotation={[-1.01, -0.45, -1.06]}
            scale={[0.19, 0.12, 0.65]}
          />
          <mesh
            name="Subdiv 410"
            geometry={nodes['Subdiv 410'].geometry}
            material={materials['Grass 1']}
            castShadow
            receiveShadow
            position={[-30.88, 69.94, 9.72]}
            rotation={[-1.37, -0.34, -1.25]}
            scale={[0.34, 0.22, 1.19]}
          />
          <mesh
            name="Subdiv 411"
            geometry={nodes['Subdiv 411'].geometry}
            material={materials['Grass 1']}
            castShadow
            receiveShadow
            position={[0.4, 46.61, -23.07]}
            rotation={[-1.87, -0.02, 2.39]}
            scale={[0.19, 0.12, 0.75]}
          />
        </group>
        <group
          name="Grass Tall 2"
          position={[943.72, -230.74, -635.21]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[-0.68, 0.68, 0.44]}
        >
          <mesh
            name="Subdiv 412"
            geometry={nodes['Subdiv 412'].geometry}
            material={materials['Grass 1']}
            castShadow
            receiveShadow
            position={[-25.73, 33.06, 9.24]}
            rotation={[-1.01, -0.45, -1.06]}
            scale={[0.19, 0.12, 0.65]}
          />
          <mesh
            name="Subdiv 413"
            geometry={nodes['Subdiv 413'].geometry}
            material={materials['Grass 1']}
            castShadow
            receiveShadow
            position={[-30.88, 69.94, 9.72]}
            rotation={[-1.37, -0.34, -1.25]}
            scale={[0.34, 0.22, 1.19]}
          />
          <mesh
            name="Subdiv 414"
            geometry={nodes['Subdiv 414'].geometry}
            material={materials['Grass 1']}
            castShadow
            receiveShadow
            position={[0.4, 46.61, -23.07]}
            rotation={[-1.87, -0.02, 2.39]}
            scale={[0.19, 0.12, 0.75]}
          />
        </group>
        <group name="Grass Tall 5" position={[-578.46, -258.37, -379.44]} scale={0.48}>
          <mesh
            name="Subdiv 415"
            geometry={nodes['Subdiv 415'].geometry}
            material={materials['Grass 1']}
            castShadow
            receiveShadow
            position={[-25.73, 33.06, 9.24]}
            rotation={[-1.01, -0.45, -1.06]}
            scale={[0.19, 0.12, 0.65]}
          />
          <mesh
            name="Subdiv 416"
            geometry={nodes['Subdiv 416'].geometry}
            material={materials['Grass 1']}
            castShadow
            receiveShadow
            position={[-30.88, 69.94, 9.72]}
            rotation={[-1.37, -0.34, -1.25]}
            scale={[0.34, 0.22, 1.19]}
          />
          <mesh
            name="Subdiv 417"
            geometry={nodes['Subdiv 417'].geometry}
            material={materials['Grass 1']}
            castShadow
            receiveShadow
            position={[0.4, 46.61, -23.07]}
            rotation={[-1.87, -0.02, 2.39]}
            scale={[0.19, 0.12, 0.75]}
          />
        </group>
        <group name="Grass Tall 6" position={[-540.32, -269, 461.6]} scale={0.33}>
          <mesh
            name="Subdiv 418"
            geometry={nodes['Subdiv 418'].geometry}
            material={materials['Grass 1']}
            castShadow
            receiveShadow
            position={[-25.73, 33.06, 9.24]}
            rotation={[-1.01, -0.45, -1.06]}
            scale={[0.19, 0.12, 0.65]}
          />
          <mesh
            name="Subdiv 419"
            geometry={nodes['Subdiv 419'].geometry}
            material={materials['Grass 1']}
            castShadow
            receiveShadow
            position={[-30.88, 69.94, 9.72]}
            rotation={[-1.37, -0.34, -1.25]}
            scale={[0.34, 0.22, 1.19]}
          />
          <mesh
            name="Subdiv 420"
            geometry={nodes['Subdiv 420'].geometry}
            material={materials['Grass 1']}
            castShadow
            receiveShadow
            position={[0.4, 46.61, -23.07]}
            rotation={[-1.87, -0.02, 2.39]}
            scale={[0.19, 0.12, 0.75]}
          />
        </group>
        <group name="Grass Tall" position={[-94.98, -244.74, 107.79]} scale={0.68}>
          <mesh
            name="Subdiv 421"
            geometry={nodes['Subdiv 421'].geometry}
            material={materials['Grass 1']}
            castShadow
            receiveShadow
            position={[-25.73, 33.06, 9.24]}
            rotation={[-1.01, -0.45, -1.06]}
            scale={[0.19, 0.12, 0.65]}
          />
          <mesh
            name="Subdiv 422"
            geometry={nodes['Subdiv 422'].geometry}
            material={materials['Grass 1']}
            castShadow
            receiveShadow
            position={[-30.88, 69.94, 9.72]}
            rotation={[-1.37, -0.34, -1.25]}
            scale={[0.34, 0.22, 1.19]}
          />
          <mesh
            name="Subdiv 423"
            geometry={nodes['Subdiv 423'].geometry}
            material={materials['Grass 1']}
            castShadow
            receiveShadow
            position={[0.4, 46.61, -23.07]}
            rotation={[-1.87, -0.02, 2.39]}
            scale={[0.19, 0.12, 0.75]}
          />
        </group>
        <group name="Grass 2" position={[487.57, -199, 442.21]}>
          <group name="Grass 3" position={[-132.13, -18.58, 0]}>
            <mesh
              name="Cube8"
              geometry={nodes.Cube8.geometry}
              material={materials.plants}
              castShadow
              receiveShadow
              position={[-60.28, 6.61, -16.31]}
              rotation={[-1.38, 0.08, -0.17]}
              scale={[0.47, 0.25, 0.02]}
            />
            <mesh
              name="Cube9"
              geometry={nodes.Cube9.geometry}
              material={materials.plants}
              castShadow
              receiveShadow
              position={[-18.08, 16.61, 60.44]}
              rotation={[-1.86, 0.08, 1.13]}
              scale={[0.5, 0.23, 0.03]}
            />
            <mesh
              name="Cube10"
              geometry={nodes.Cube10.geometry}
              material={materials.plants}
              castShadow
              receiveShadow
              position={[56.31, 9.21, -34.78]}
              rotation={[-1.45, -0.02, -2.62]}
              scale={[0.45, 0.25, 0.02]}
            />
            <mesh
              name="Cube11"
              geometry={nodes.Cube11.geometry}
              material={materials.plants}
              castShadow
              receiveShadow
              position={[51.82, -5.82, 43.29]}
              rotation={[-1.44, -0.06, 2.54]}
              scale={[0.5, 0.24, 0.02]}
            />
            <mesh
              name="Cube12"
              geometry={nodes.Cube12.geometry}
              material={materials.plants}
              castShadow
              receiveShadow
              position={[-7.08, 24.92, -67.84]}
              rotation={[-1.13, 0.01, -1.51]}
              scale={[0.52, 0.23, 0.03]}
            />
          </group>
          <mesh
            name="Cube13"
            geometry={nodes.Cube13.geometry}
            material={materials.plants}
            castShadow
            receiveShadow
            position={[-60.28, 6.61, -16.31]}
            rotation={[-1.38, 0.08, -0.17]}
            scale={[0.47, 0.25, 0.02]}
          />
          <mesh
            name="Cube14"
            geometry={nodes.Cube14.geometry}
            material={materials.plants}
            castShadow
            receiveShadow
            position={[-18.08, 16.61, 60.44]}
            rotation={[-1.86, 0.08, 1.13]}
            scale={[0.5, 0.23, 0.03]}
          />
          <mesh
            name="Cube15"
            geometry={nodes.Cube15.geometry}
            material={materials.plants}
            castShadow
            receiveShadow
            position={[56.31, 9.21, -34.78]}
            rotation={[-1.45, -0.02, -2.62]}
            scale={[0.45, 0.25, 0.02]}
          />
          <mesh
            name="Cube16"
            geometry={nodes.Cube16.geometry}
            material={materials.plants}
            castShadow
            receiveShadow
            position={[51.82, -5.82, 43.29]}
            rotation={[-1.44, -0.06, 2.54]}
            scale={[0.5, 0.24, 0.02]}
          />
          <mesh
            name="Cube17"
            geometry={nodes.Cube17.geometry}
            material={materials.plants}
            castShadow
            receiveShadow
            position={[-7.08, 24.92, -67.84]}
            rotation={[-1.13, 0.01, -1.51]}
            scale={[0.52, 0.23, 0.03]}
          />
        </group>
        <group name="Grass 31" position={[118.95, -199, 558.18]}>
          <mesh
            name="Cube18"
            geometry={nodes.Cube18.geometry}
            material={materials.plants}
            castShadow
            receiveShadow
            position={[-60.28, 6.61, -16.31]}
            rotation={[-1.38, 0.08, -0.17]}
            scale={[0.47, 0.25, 0.02]}
          />
          <mesh
            name="Cube19"
            geometry={nodes.Cube19.geometry}
            material={materials.plants}
            castShadow
            receiveShadow
            position={[-18.08, 16.61, 60.44]}
            rotation={[-1.86, 0.08, 1.13]}
            scale={[0.5, 0.23, 0.03]}
          />
          <mesh
            name="Cube20"
            geometry={nodes.Cube20.geometry}
            material={materials.plants}
            castShadow
            receiveShadow
            position={[56.31, 9.21, -34.78]}
            rotation={[-1.45, -0.02, -2.62]}
            scale={[0.45, 0.25, 0.02]}
          />
          <mesh
            name="Cube21"
            geometry={nodes.Cube21.geometry}
            material={materials.plants}
            castShadow
            receiveShadow
            position={[51.82, -5.82, 43.29]}
            rotation={[-1.44, -0.06, 2.54]}
            scale={[0.5, 0.24, 0.02]}
          />
          <mesh
            name="Cube22"
            geometry={nodes.Cube22.geometry}
            material={materials.plants}
            castShadow
            receiveShadow
            position={[-7.08, 24.92, -67.84]}
            rotation={[-1.13, 0.01, -1.51]}
            scale={[0.52, 0.23, 0.03]}
          />
        </group>
        <group name="Grass" position={[607, -199, 442.21]}>
          <mesh
            name="Cube23"
            geometry={nodes.Cube23.geometry}
            material={materials.plants}
            castShadow
            receiveShadow
            position={[-60.28, 6.61, -16.31]}
            rotation={[-1.38, 0.08, -0.17]}
            scale={[0.47, 0.25, 0.02]}
          />
          <mesh
            name="Cube24"
            geometry={nodes.Cube24.geometry}
            material={materials.plants}
            castShadow
            receiveShadow
            position={[-18.08, 16.61, 60.44]}
            rotation={[-1.86, 0.08, 1.13]}
            scale={[0.5, 0.23, 0.03]}
          />
          <mesh
            name="Cube25"
            geometry={nodes.Cube25.geometry}
            material={materials.plants}
            castShadow
            receiveShadow
            position={[56.31, 9.21, -34.78]}
            rotation={[-1.45, -0.02, -2.62]}
            scale={[0.45, 0.25, 0.02]}
          />
          <mesh
            name="Cube26"
            geometry={nodes.Cube26.geometry}
            material={materials.plants}
            castShadow
            receiveShadow
            position={[51.82, -5.82, 43.29]}
            rotation={[-1.44, -0.06, 2.54]}
            scale={[0.5, 0.24, 0.02]}
          />
          <mesh
            name="Cube27"
            geometry={nodes.Cube27.geometry}
            material={materials.plants}
            castShadow
            receiveShadow
            position={[-7.08, 24.92, -67.84]}
            rotation={[-1.13, 0.01, -1.51]}
            scale={[0.52, 0.23, 0.03]}
          />
        </group>
        <group
          name="Round Fence 2"
          position={[-843.32, -262.79, 784.46]}
          rotation={[0, 0.13, 0.03]}
          scale={[1.72, 1, 4.92]}
        >
          <mesh
            name="Merged Geometry3"
            geometry={nodes['Merged Geometry3'].geometry}
            material={materials.red}
            castShadow
            receiveShadow
            position={[0, 125.03, 4.89]}
          />
          <mesh
            name="Cube 27"
            geometry={nodes['Cube 27'].geometry}
            material={materials.red}
            castShadow
            receiveShadow
            position={[0, 70.14, -4.89]}
            rotation={[0, 0, 0]}
            scale={[2.66, 0.18, 0.04]}
          />
          <mesh
            name="Cube28"
            geometry={nodes.Cube28.geometry}
            material={materials.red}
            castShadow
            receiveShadow
            position={[0, 173.73, -4.89]}
            rotation={[0, 0, 0]}
            scale={[2.66, 0.18, 0.04]}
          />
        </group>
        <mesh
          name="Rectangle"
          geometry={nodes.Rectangle.geometry}
          material={materials['Rectangle Material']}
          castShadow
          receiveShadow
          position={[357.76, -316.78, 89.66]}
          rotation={[-1.59, -0.02, 0.13]}
          scale={[1.77, 1.15, 1]}
        />
        <group name="Group 2" position={[310.89, 126.55, -23.65]}>
          <mesh
            name="Torus2"
            geometry={nodes.Torus2.geometry}
            material={materials['Torus2 Material']}
            castShadow
            receiveShadow
            position={[-208.45, 250.97, 53.31]}
            rotation={[-1.65, -0.76, -1.61]}
            scale={[1, 1, 0.74]}
          />
          <mesh
            name="Ellipse 5"
            geometry={nodes['Ellipse 5'].geometry}
            material={materials['Ellipse 5 Material']}
            castShadow
            receiveShadow
            position={[-171.54, 280.07, 63.71]}
            rotation={[0.05, -0.01, -0.19]}
            scale={1}
          />
          <mesh
            name="Ellipse 4"
            geometry={nodes['Ellipse 4'].geometry}
            material={materials['Ellipse 4 Material']}
            castShadow
            receiveShadow
            position={[226.88, 251.98, 9.32]}
            rotation={[-0.09, 0.05, 0.01]}
            scale={1}
          />
          <mesh
            name="Cylinder 5"
            geometry={nodes['Cylinder 5'].geometry}
            material={materials['Cylinder 5 Material']}
            castShadow
            receiveShadow
            position={[98.65, -56.92, 277.27]}
            rotation={[-0.19, 0.11, -0.05]}
            scale={[1, 1.51, 1]}
          />
          <mesh
            name="Cylinder 4"
            geometry={nodes['Cylinder 4'].geometry}
            material={materials['Cylinder 4 Material']}
            castShadow
            receiveShadow
            position={[49.29, -54.69, 282.22]}
            rotation={[-0.19, 0.11, -0.05]}
            scale={[1, 1.51, 1]}
          />
          <mesh
            name="Cube 10"
            geometry={nodes['Cube 10'].geometry}
            material={materials['Cube 10 Material']}
            castShadow
            receiveShadow
            position={[103.15, 183.82, 165.77]}
            rotation={[0, 0, 0]}
            scale={[1.86, 1, 1.19]}
          />
          <mesh
            name="Cube29"
            geometry={nodes.Cube29.geometry}
            material={materials['Cube29 Material']}
            castShadow
            receiveShadow
            position={[124.38, 50.64, 298.04]}
            rotation={[0, 0, 0]}
            scale={[1.86, 1.66, 1.19]}
          />
          <mesh
            name="Cube30"
            geometry={nodes.Cube30.geometry}
            material={materials['Cube30 Material']}
            castShadow
            receiveShadow
            position={[41.48, 53.04, 302.67]}
            rotation={[0, 0, 0]}
            scale={[1.86, 1.66, 1.19]}
          />
          <mesh
            name="Cube 9"
            geometry={nodes['Cube 9'].geometry}
            material={materials['Cube 9 Material']}
            castShadow
            receiveShadow
            position={[23.2, 187.58, 176.35]}
            rotation={[0, 0, 0]}
            scale={[1.86, 1, 1.19]}
          />
          <mesh
            name="Cube 61"
            geometry={nodes['Cube 61'].geometry}
            material={materials['Cube 61 Material']}
            castShadow
            receiveShadow
            position={[56.61, 38.93, 232.39]}
            rotation={[0, 0.1, 0]}
            scale={[1, 1, 0.44]}
          />
          <mesh
            name="Ellipse 21"
            geometry={nodes['Ellipse 21'].geometry}
            material={materials['Ellipse 21 Material']}
            castShadow
            receiveShadow
            position={[-174.97, 279.16, 47.08]}
            rotation={[0, 0, 0]}
          />
          <mesh
            name="Ellipse1"
            geometry={nodes.Ellipse1.geometry}
            material={materials['Ellipse1 Material']}
            castShadow
            receiveShadow
            position={[225.53, 249.19, -9.14]}
            rotation={[0, 0, 0]}
          />
          <mesh
            name="Cylinder 3"
            geometry={nodes['Cylinder 3'].geometry}
            material={materials['Cylinder 3 Material']}
            castShadow
            receiveShadow
            position={[-62.11, 348.28, 46.68]}
            rotation={[0.22, 0.09, 0.27]}
            scale={[1, 1.51, 1]}
          />
          <mesh
            name="Cylinder"
            geometry={nodes.Cylinder.geometry}
            material={materials['Cylinder Material']}
            castShadow
            receiveShadow
            position={[117.25, 348, 7.86]}
            rotation={[0.22, 0.09, -0.27]}
            scale={[1, 1.51, 1]}
          />
          <mesh
            name="Cube 11"
            geometry={nodes['Cube 11'].geometry}
            material={materials['Cube 11 Material']}
            castShadow
            receiveShadow
            position={[0, -30.4, -34.05]}
            rotation={[0, 0, 0]}
          >
            <mesh
              name="Cube 12"
              geometry={nodes['Cube 12'].geometry}
              material={materials['Cube 12 Material']}
              castShadow
              receiveShadow
              position={[36.01, -190.54, 261.69]}
              rotation={[-0.08, 0, 0]}
              scale={1}
            />
          </mesh>
        </group>
        <mesh
          name="Cube 51"
          geometry={nodes['Cube 51'].geometry}
          material={materials['Cube 51 Material']}
          castShadow
          receiveShadow
          position={[566.37, -141.22, 238.68]}
          rotation={[2.94, -0.95, -0.17]}
          scale={[1.12, 1, 1]}
        />
        <mesh
          name="Cube 28"
          geometry={nodes['Cube 28'].geometry}
          material={materials['Cube 28 Material']}
          castShadow
          receiveShadow
          position={[183.05, 4.66, 235.46]}
          rotation={[2.4, -0.14, 1.72]}
          scale={[1, 1.79, 1]}
        />
        <mesh
          name="Cube 31"
          geometry={nodes['Cube 31'].geometry}
          material={materials['Cube 31 Material']}
          castShadow
          receiveShadow
          position={[541.53, -30.4, 193.12]}
          rotation={[2.39, -0.01, 1.57]}
          scale={[1, 1.79, 1]}
        />
        <mesh
          name="Cube 46"
          geometry={nodes['Cube 46'].geometry}
          material={materials['Cube 46 Material']}
          castShadow
          receiveShadow
          position={[78.62, -124.91, 221.13]}
          rotation={[0.27, 0.93, -0.33]}
          scale={1}
        />
        <directionalLight
          name="Directional Light3"
          castShadow
          intensity={0.7}
          shadow-mapSize-width={1024}
          shadow-mapSize-height={1024}
          shadow-camera-near={-10000}
          shadow-camera-far={100000}
          shadow-camera-left={-1000}
          shadow-camera-right={1000}
          shadow-camera-top={1000}
          shadow-camera-bottom={-1000}
          position={[2161.79, 120.15, -922.43]}
          rotation={[0, 0, 0]}
        />
        <OrthographicCamera
          name="1"
          makeDefault={true}
          zoom={0.17}
          far={100000}
          near={-100000}
          position={[3065.91, 4150.1, 1830.24]}
          rotation={[-0.89, 0.5, 0.53]}
          scale={1}
        />
        <CameraControls />
        <hemisphereLight name="Default Ambient Light" intensity={0.75} color="#eaeaea" />
      </group>
    </>
  )
}
